### ISSUE TITLE
No profiles returned

### ISSUE THREAD

**Issue by shoekstra** [chef/okta_aws#11]
Hi,

When running `./okta_aws.sh -l` I get an empty profile list:

```
Available profiles:

```

I've tried configuring `role_arn` as the okta name you select via the portal and the ARN of the role, but still no luck.

My config is pretty minimal, 

```
[general]
username = "myuser"
okta_server = "mytenant.okta-emea.com"

[some-profile-name]
role_arn = "arn:aws:iam::123456788901:role/admins"
```

Anything I can try or am missing?

**Comment by jtimberman** [comment]
@shoekstra Sorry we haven't replied to this issue! 

Did you get this working? if so, do you remember the solution and can you post it here?

**Comment by shoekstra** [comment]
I went back to what I was using before - I'll give it another go as I'm not overly happy with how I do it now.

**Comment by shoekstra** [comment]
@jtimberman Installed the latest version and still same result.

I can authenticate, get the cookie, no profiles returned using `--list`.

**Comment by jtimberman** [comment]
Again, sorry we didn't follow up here. Version 0.6.0 returns a list for me for all the AWS accounts in my Okta profile. Please try the latest version (it's available via homebrew or pypi) and reopen this issue if it's still a problem.
