### ISSUE TITLE
Support MFA

### ISSUE THREAD

**Issue by bw-z** [chef/okta_aws#15]
Returns an error when MFA Auth is required

**Comment by mivok** [comment]
Hi. Thank you for your issue report. You are absolutely right, okta_aws doesn't currently support MFA requests from okta. No promises on when, but it's on the list of features we want to add.

**Comment by mivok** [comment]
MFA Support was added in https://github.com/chef/okta_aws/pull/16 and will be included in the next release.

This only applies when you have a global sign on policy that requires MFA (in other words, you're prompted for MFA when logging into okta). If you require MFA only for specific applications, then some more work is required to support this in okta_aws.

**Comment by nickperkins** [comment]
Just a note that #16 only supports TOTP MFA at the moment.

**Comment by jtimberman** [comment]
Version 0.6.0 was released with MFA support.
