### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by etendards** [chef/okta_aws#3]
$ ./okta_aws
Okta Username: e
Okta Password:
Getting SAML assertion from okta... Traceback (most recent call last):
  File "./okta_aws", line 233, in <module>
    oa.run()
  File "./okta_aws", line 197, in run
    assertion = self.okta.get_saml_assertion()
  File "./okta_aws", line 85, in get_saml_assertion
    return self.assertion(self.saml())
  File "./okta_aws", line 104, in saml
    resp.status_code)
Exception: Received error code from server: 404

-----------------------------------------------------------
[general]
username="first.last"
okta_server="e.oktapreview.com"
apptype="amazon_aws"

[default]
appid="0oab5djefnTb4cMht0h7"
principal_arn="arn:aws:iam::1111111:saml-provider/Okta-preview"
role_arn="arn:aws:iam::11111111:role/CloudAdmins"

**Comment by joshbrand** [comment]
could you give this a shot with the newer version?  We've made a bunch of bugfixes (note changes in the config toml though!)

**Comment by joshbrand** [comment]
if you're still seeing issues, feel free to reopen!
